### ISSUE TITLE
Segfault when WAD symlink path is non-existent

### ISSUE THREAD

**Issue by lukassup** [coelckers/gzdoom#1269]
# Repro

```
user@computer ~/.config/gzdoom % ln -s nonexistent.wad doom2.wad
user@computer ~/.config/gzdoom % gzdoom 
GZDoom g4.6pre-46-ge6c71c2f0-m - 2021-01-05 11:09:19 -0500 - SDL version
Compiled on Jan  5 2021

OS: Arch Linux, Linux 5.10.4-zen2-1-zen on x86_64
M_LoadDefaults: Load system defaults.


*** Fatal Error ***
!!! Failed to exec debug process
[1]    23642 segmentation fault (core dumped)  gzdoom
```

# Backtrace

```
(gdb) backtrace 
#0  0x00007f1b7b538f75 in raise () at /usr/lib/libpthread.so.0
#1  0x0000559fa9073008 in  ()
#2  0x00007f1b7b5390f0 in <signal handler called> () at /usr/lib/libpthread.so.0
#3  0x0000559fa9601594 in FileSystem::InitMultipleFiles(TArray<FString, FString>&, bool, LumpFilterInfo*) ()
#4  0x0000559fa9601754 in FileSystem::InitSingleFile(char const*, bool) ()
#5  0x0000559fa92ac646 in FIWadManager::ScanIWAD(char const*) ()
#6  0x0000559fa92ada17 in FIWadManager::ValidateIWADs() ()
#7  0x0000559fa92ae42b in FIWadManager::IdentifyVersion(TArray<FString, FString>&, char const*, char const*, char const*) ()
#8  0x0000559fa92af6bf in FIWadManager::FindIWAD(TArray<FString, FString>&, char const*, char const*, char const*) ()
#9  0x0000559fa92b5ea3 in  ()
#10 0x0000559fa92b8a43 in GameMain() ()
#11 0x0000559fa9055145 in main ()
```

# Fix

```
139 user@computer ~/.config/gzdoom % rm doom2.wad
user@computer ~/.config/gzdoom % gzdoom      
GZDoom g4.6pre-46-ge6c71c2f0-m - 2021-01-05 11:09:19 -0500 - SDL version
Compiled on Jan  5 2021

OS: Arch Linux, Linux 5.10.4-zen2-1-zen on x86_64
M_LoadDefaults: Load system defaults.
```

**Comment by Cacodemon345** [comment]
This should be closed.
